package cn.et.food.entity;

public class Foods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foods.foodid
     *
     * @mbg.generated Sat Dec 09 08:54:39 CST 2017
     */
    private Integer foodid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foods.foodname
     *
     * @mbg.generated Sat Dec 09 08:54:39 CST 2017
     */
    private String foodname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foods.price
     *
     * @mbg.generated Sat Dec 09 08:54:39 CST 2017
     */
    private Double price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foods.foodid
     *
     * @return the value of foods.foodid
     *
     * @mbg.generated Sat Dec 09 08:54:39 CST 2017
     */
    public Integer getFoodid() {
        return foodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foods.foodid
     *
     * @param foodid the value for foods.foodid
     *
     * @mbg.generated Sat Dec 09 08:54:39 CST 2017
     */
    public void setFoodid(Integer foodid) {
        this.foodid = foodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foods.foodname
     *
     * @return the value of foods.foodname
     *
     * @mbg.generated Sat Dec 09 08:54:39 CST 2017
     */
    public String getFoodname() {
        return foodname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foods.foodname
     *
     * @param foodname the value for foods.foodname
     *
     * @mbg.generated Sat Dec 09 08:54:39 CST 2017
     */
    public void setFoodname(String foodname) {
        this.foodname = foodname == null ? null : foodname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foods.price
     *
     * @return the value of foods.price
     *
     * @mbg.generated Sat Dec 09 08:54:39 CST 2017
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foods.price
     *
     * @param price the value for foods.price
     *
     * @mbg.generated Sat Dec 09 08:54:39 CST 2017
     */
    public void setPrice(Double price) {
        this.price = price;
    }
}