package cn.et.food.dao;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

import cn.et.food.entity.Foods;
import cn.et.food.entity.FoodsExample;

public interface FoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foods
     *
     * @mbg.generated Wed Dec 20 11:04:51 CST 2017
     */
    @SelectProvider(type=FoodsSqlProvider.class, method="countByExample")
    long countByExample(FoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foods
     *
     * @mbg.generated Wed Dec 20 11:04:51 CST 2017
     */
    @DeleteProvider(type=FoodsSqlProvider.class, method="deleteByExample")
    int deleteByExample(FoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foods
     *
     * @mbg.generated Wed Dec 20 11:04:51 CST 2017
     */
    @Delete({
        "delete from foods",
        "where foodid = #{foodid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer foodid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foods
     *
     * @mbg.generated Wed Dec 20 11:04:51 CST 2017
     */
    @Insert({
        "insert into foods (foodid, foodname, ",
        "price)",
        "values (#{foodid,jdbcType=INTEGER}, #{foodname,jdbcType=VARCHAR}, ",
        "#{price,jdbcType=DOUBLE})"
    })
    int insert(Foods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foods
     *
     * @mbg.generated Wed Dec 20 11:04:51 CST 2017
     */
    @InsertProvider(type=FoodsSqlProvider.class, method="insertSelective")
    int insertSelective(Foods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foods
     *
     * @mbg.generated Wed Dec 20 11:04:51 CST 2017
     */
    @SelectProvider(type=FoodsSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="foodid", property="foodid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="foodname", property="foodname", jdbcType=JdbcType.VARCHAR),
        @Result(column="price", property="price", jdbcType=JdbcType.DOUBLE)
    })
    List<Foods> selectByExampleWithRowbounds(FoodsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foods
     *
     * @mbg.generated Wed Dec 20 11:04:51 CST 2017
     */
    @SelectProvider(type=FoodsSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="foodid", property="foodid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="foodname", property="foodname", jdbcType=JdbcType.VARCHAR),
        @Result(column="price", property="price", jdbcType=JdbcType.DOUBLE)
    })
    List<Foods> selectByExample(FoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foods
     *
     * @mbg.generated Wed Dec 20 11:04:51 CST 2017
     */
    @Select({
        "select",
        "foodid, foodname, price",
        "from foods",
        "where foodid = #{foodid,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="foodid", property="foodid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="foodname", property="foodname", jdbcType=JdbcType.VARCHAR),
        @Result(column="price", property="price", jdbcType=JdbcType.DOUBLE)
    })
    Foods selectByPrimaryKey(Integer foodid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foods
     *
     * @mbg.generated Wed Dec 20 11:04:51 CST 2017
     */
    @UpdateProvider(type=FoodsSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Foods record, @Param("example") FoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foods
     *
     * @mbg.generated Wed Dec 20 11:04:51 CST 2017
     */
    @UpdateProvider(type=FoodsSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Foods record, @Param("example") FoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foods
     *
     * @mbg.generated Wed Dec 20 11:04:51 CST 2017
     */
    @UpdateProvider(type=FoodsSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Foods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foods
     *
     * @mbg.generated Wed Dec 20 11:04:51 CST 2017
     */
    @Update({
        "update foods",
        "set foodname = #{foodname,jdbcType=VARCHAR},",
          "price = #{price,jdbcType=DOUBLE}",
        "where foodid = #{foodid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Foods record);
}